### PR TITLE
Extra call backs

### PR DESCRIPTION
**Pull request by Merdeka**
Added a call-back for OPC_MULTI_SENSE. It it used by Uhlenbrock for the 68500 MARCo-Empfänger

### CODE REVIEW

**Comment by Merdeka** [comment]
Went through the JMRI Source code and turns out that Al Silverstein had already reverse engineered the OPC_MULTI_SENSE. So I used the JMRI and Rocrail CGA sources to update the code.

I could use a push in the right direction regarding the:  LocoNetClass::processSwitchSensorMessage does not seem to be the correct place for triggering callback functions for OPC_MULTI_SENSE messages.

Do you mean adding something like: uint8_t LocoNetClass::processPowerTransponderMessage( lnMsg *LnPacket )

I'm not familiar how to do that to be honest.

**Comment by kiwi64ajs** [comment]
Hi,

I saw this merge request come in and to be honest I’m not fully sure with the mechanics of how to deal with it as I’m still very much a Git novice but one of the young guys at work will be able to guide me along the path the Git Success… ;)

I was just thinking about adding support for some of the uses of those OPC_MULTI_SENSE packets PM42 and UP90 etc for my own layout so you code contribution was quite timely.
> Went through the JMRI Source code and turns out that Al Silverstein had already reverse engineered the OPC_MULTI_SENSE. So I used the JMRI and Rocrail CGA sources to update the code.
> 
Yeah, there’s a treasure-trove of good information regarding decoding LocoNet packets in JMRI as Bob J got an agreement with AJ at Digitrax that JMRI could use packets not covered in the Personal Edition LocoNet Protocol spec as long as we didn’t make it obvious and add lots of documentation in the code that would leak detail unnecessarily… ;)

I have the same agreement with my library hence some of the wording in the header of the files.
> I could use a push in the right direction regarding the: LocoNetClass::processSwitchSensorMessage does not seem to be the correct place for triggering callback functions for OPC_MULTI_SENSE messages.
> 
> Do you mean adding something like: uint8_t LocoNetClass::processPowerTransponderMessage( lnMsg *LnPacket )
> 
In my revised LocoNet2 library I have merged all those processXXX methods into a single method so for now just add it to the end of: processSwitchSensorMessage()

Also just looking at the comments in the GitHub I would suggest adding additional notifyXXX() call-backs for PM42 zone state changes notifyPowerManager(), another for the Uhlenbrock 68500 MARCo-Empfänger that notifies as a Loco enters/exits the blocks etc.

HTH

Alex

**Comment by bobjacobsen** [comment]
@kiwi64ajs If there are no conflicts between the submitted code and what's in the repository already, at the bottom of the PR page (right below this comment now) you should see:

merge

Just click the "Merge pull request" button to do the merge, or click the "command line instructions" link for the exact commands needed to pull it out to a local copy for compiling, testing, etc.

If there are conflicts, it looks like this:

conflict

and you have to follow the instructions for manual merge so you can fix them.

**Comment by Merdeka** [comment]
Yes, thanks Bob.

**Comment by kiwi64ajs** [comment]
I've pulled your branch into my local repository and will do a bit of experimenting with it and also look closer at my LocoNet Developers Spec docs (version 1.2c) and tweak some of your terms etc to make it match-up to the docs better and also allow for a few more things that might not be apparent without the spec docs... ;)

**Pull request merged**
