### PR TITLE
Add support for ESP8266 platform

### PR DESCRIPTION
**Pull request by bjoernrennfanz**
This PR adds support for using LocoNet library with cheap ESP8266 microcontrollers. The implementation uses pin change interrupts and hardware timer1 to generate signals with accurate timmings.

### CODE REVIEW

**Comment by kiwi64ajs** [comment]
Hi Björn,

Wow, that’s pretty cool.

I had wondered for years about the viability of running the LocoNet library on a ESP8266 to make a WiThrottle Gateway, but presumed the Wi-Fi interrupts and CPU load would pre-empt the LocoNet comms too much and cause comms errors or packet loss (or both) and figured I’d wait until the ESP32. However, life keeps getting in the way and I’ve not progressed the idea on either chip - so good to see you’ve done something.

Have you been able to give it a good load-test to verify how robust the LocoNet Rx/Tx is under Wi-Fi load? 

We can certainly merge in you code (after I take a long hard look at it…) but I was hoping to move away from hacking more platforms into the AVR code-base and move the future to the LocoNet2 library (see: https://github.com/mrrwa/LocoNet2 <https://github.com/mrrwa/LocoNet2>) that attempted to split things out more and provide separate platform support in separate files and sub-classes.

Anyway I’ll try and get to looking at you code this week so I can respond more specifically.

HTH

Alex Shepherd

**Comment by bjoernrennfanz** [comment]
Hi, i used that implementation for an ESP8266 to implement an WiFi LocoNet Buffer an drive the trains using RocRail. Currently i have no issues doing this with my implementation.

**Comment by bjoernrennfanz** [comment]
Hi, resolved the rebase issues and pushed that again.

**Comment by kiwi64ajs** [comment]
Hi Björn,
I had to manually resolve merge conflicts using the Web Editor for this PR as it conflicted quite badly with the STM32 support that also got merged recently.
When you get a chance can you please take a look at the resulting code and see if I've broken stuff or not.
Regards
Alex

**Pull request merged**
